name: Build and Check Code Quality for Staging

on:
  push:
    branches:
      - staging

jobs:
  SonarCloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=parisyanaylah
            -Dsonar.projectKey=ParisyaNaylah_Ecommerce-project
            -Dsonar.python.coverage.reportPaths=coverage.xml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10' # Atur sesuai versi Node.js yang kamu gunakan

      - name: Install dependencies
        run: |
          npm install

      - name: Run Jest Tests
        run: |
          npm test -- --coverage
        continue-on-error: true  # Jika ingin melanjutkan meskipun ada error pada test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Sesuaikan dengan versi Node.js yang kamu gunakan

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npm run lint
        continue-on-error: true  # Jika ingin melanjutkan meskipun ada error di linting

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/e-commerce:staging
